//! The campaign report. Pure function of its parameters: no clock, no randomness beyond the
//! seeds, so `scripts/report.sh --check` can insist the committed copy matches the code.

use shoke_core::Invariant;
use shoke_jev::provider::{COLD_START_MS, IDLE_COLD_MS};
use shoke_jev::{
    default_set, minimal, sweep, Bug, Config, FaultKind, JevFault, Mix, Profile, Scenario,
    SweepOpts, SweepResult,
};
use std::fmt::Write;

const COLUMNS: [&str; 6] = ["I1", "I2", "I3", "I4", "I5", "I7"];

struct Row {
    label: String,
    cfg: Config,
    /// Whether the I7 policy invariant applies to this row.
    policy: bool,
}

fn rows() -> Vec<Row> {
    let mut rows = Vec::new();
    let mut add = |label: &str, profile: Profile, floor: bool, bugs: &[Bug], policy: bool| {
        let mut cfg = Config::new(profile);
        cfg.floor = floor;
        cfg.bugs = bugs.iter().copied().collect();
        rows.push(Row {
            label: label.to_string(),
            cfg,
            policy,
        });
    };
    add("jev, no floor", Profile::Jev, false, &[], true);
    add("jev, with floor", Profile::Jev, true, &[], true);
    add("kev warm, no floor", Profile::KevWarm, false, &[], true);
    add(
        "kev scale-to-zero, no floor",
        Profile::KevScaleToZero,
        false,
        &[],
        true,
    );
    add(
        "kev scale-to-zero, with floor",
        Profile::KevScaleToZero,
        true,
        &[],
        true,
    );
    for bug in Bug::ALL {
        let floor = matches!(bug, Bug::CacheFallback);
        let label = format!(
            "jev + `{}`{}",
            bug.name(),
            if floor { " (with floor)" } else { "" }
        );
        add(&label, Profile::Jev, floor, &[bug], false);
    }
    rows
}

fn cell(result: &SweepResult, id: &str, applies: bool) -> String {
    if !applies {
        return "n/a".to_string();
    }
    result.count(id).to_string()
}

fn describe_fault(f: &JevFault) -> String {
    let kind = match f.kind {
        FaultKind::Http(c) => format!("http {c}"),
        FaultKind::Slow(x) => format!("slow +{x} ms"),
        FaultKind::ColdStart => "cold start".to_string(),
        FaultKind::Truncate => "truncated answer".to_string(),
        FaultKind::OutOfMenu => "out-of-menu answer".to_string(),
    };
    format!("{kind} for {} ms from t={} ms", f.dur, f.at)
}

pub fn render(seeds: u64, requests: usize, faults: usize, max_runs: u32) -> String {
    let mut out = String::new();
    let w = &mut out;
    let opts = SweepOpts {
        start: 0,
        seeds,
        requests,
        faults,
        mix: Mix::All,
    };

    writeln!(w, "# Sybershoke report: the Jev/Kev decision path\n").unwrap();
    writeln!(
        w,
        "Generated by `shoke report`. Do not edit by hand: `scripts/report.sh --check` fails when \
         this file differs from what the code produces.\n"
    )
    .unwrap();
    writeln!(w, "## What this is, and is not\n").unwrap();
    writeln!(
        w,
        "This is a **model**, written from the SyberLabs project documents. It is not the RISE \
         Worker, and it never calls Jev or Kev. It reproduces the structure those documents \
         describe: an 8000 ms deadline, a Kev scale-to-zero cold start of about {COLD_START_MS} ms, \
         a keyword override that forces the night-drive look, a decision cache, and a menu that \
         answers are validated against. A finding here is a finding about that structure. Whether the \
         real Worker has the same failure needs the phase 2 adapter run against recorded fixtures.\n"
    )
    .unwrap();
    writeln!(
        w,
        "Two numbers are **assumptions**, not measurements: the idle time before a scale-to-zero \
         host goes cold ({IDLE_COLD_MS} ms; the docs give the cold-start cost but not this \
         threshold) and the traffic pattern (about one request in twelve follows a gap of 130 to \
         200 seconds). Both are constants in `crates/shoke-jev`; change them and rerun.\n"
    )
    .unwrap();
    writeln!(
        w,
        "Parameters: {seeds} seeds (0 to {}), {requests} requests per seed, {faults} faults per \
         seed drawn from every class, deadline 8000 ms, at most 2 provider calls per request.\n",
        seeds.saturating_sub(1)
    )
    .unwrap();

    // Table 1: configurations.
    writeln!(w, "## 1. Configurations\n").unwrap();
    writeln!(
        w,
        "Each cell is the number of seeds (of {seeds}) on which the invariant failed. `n/a` means \
         the row does not apply the I7 policy. I7 is a policy, not a bug: it asks that every \
         request be answered with a plan even when the provider fails, which needs a preset floor.\n"
    )
    .unwrap();
    writeln!(
        w,
        "Read the `kev scale-to-zero` I7 count as a demonstration of the mechanism, not a failure \
         rate. It is driven by the *assumed* traffic: a request that arrives after a long idle gap \
         and misses the cache meets a {COLD_START_MS} ms cold start against an 8000 ms deadline, so \
         nearly every seed contains one. Real traffic decides how often that happens. The \
         `with floor` row shows the floor removes it entirely, which holds whatever the traffic.\n"
    )
    .unwrap();
    writeln!(w, "| Configuration | {} |", COLUMNS.join(" | ")).unwrap();
    writeln!(w, "|---|{}", "---:|".repeat(COLUMNS.len())).unwrap();
    let rows = rows();
    for row in &rows {
        let invs = default_set(row.policy);
        let result = sweep(&row.cfg, &opts, &invs);
        let cells: Vec<String> = COLUMNS
            .iter()
            .map(|id| cell(&result, id, *id != "I7" || row.policy))
            .collect();
        writeln!(w, "| {} | {} |", row.label, cells.join(" | ")).unwrap();
    }

    // Table 2: seeded bugs and their smallest reproductions.
    writeln!(w, "\n## 2. Seeded bugs and their smallest reproductions\n").unwrap();
    writeln!(
        w,
        "Each bug removes one safeguard. The shrinker takes the first failing seed and removes \
         faults, then shortens and moves the survivors, until the failure needs nothing more.\n"
    )
    .unwrap();
    writeln!(
        w,
        "| Bug | Caught by | Seeds caught | First seed | Faults before | Smallest reproduction |"
    )
    .unwrap();
    writeln!(w, "|---|---|---:|---:|---:|---|").unwrap();
    for bug in Bug::ALL {
        let mut cfg = Config::new(Profile::Jev);
        cfg.floor = matches!(bug, Bug::CacheFallback);
        cfg.bugs.insert(bug);
        let invs: Vec<Box<dyn Invariant>> = default_set(false);
        let result = sweep(&cfg, &opts, &invs);
        let caught = result.count(bug.target());
        match result.first_seed.get(bug.target()) {
            None => {
                writeln!(
                    w,
                    "| `{}` | {} | 0 | none | n/a | not caught |",
                    bug.name(),
                    bug.target()
                )
                .unwrap();
            }
            Some(&seed) => {
                let sc = Scenario::generate(seed, requests, faults, Mix::All);
                let min = minimal(&cfg, &sc, &invs, bug.target(), max_runs);
                let repro = if min.faults.is_empty() {
                    "no faults needed".to_string()
                } else {
                    min.faults
                        .iter()
                        .map(describe_fault)
                        .collect::<Vec<_>>()
                        .join("; ")
                };
                writeln!(
                    w,
                    "| `{}` | {} | {} | {} | {} | {} |",
                    bug.name(),
                    bug.target(),
                    caught,
                    seed,
                    sc.faults.len(),
                    repro
                )
                .unwrap();
            }
        }
    }

    // Table 3: which fault class finds which bug.
    writeln!(w, "\n## 3. Which fault class finds which bug\n").unwrap();
    writeln!(
        w,
        "Seeds (of {seeds}) on which the bug's target invariant failed, when only one class of \
         fault is injected ({faults} faults per seed). A bug that needs one specific class can be \
         diluted when every class is mixed together, and a bug that needs none is found by a run \
         with no faults at all.\n"
    )
    .unwrap();
    let mixes = [
        Mix::All,
        Mix::Http,
        Mix::Slow,
        Mix::Cold,
        Mix::Truncate,
        Mix::OutOfMenu,
    ];
    let mut header = String::from("| Bug (target) | no faults |");
    let mut rule = String::from("|---|---:|");
    for m in &mixes {
        write!(header, " {} |", m.name()).unwrap();
        rule.push_str("---:|");
    }
    writeln!(w, "{header}").unwrap();
    writeln!(w, "{rule}").unwrap();
    for bug in Bug::ALL {
        let mut cfg = Config::new(Profile::Jev);
        cfg.floor = matches!(bug, Bug::CacheFallback);
        cfg.bugs.insert(bug);
        let invs = default_set(false);
        let none = sweep(&cfg, &SweepOpts { faults: 0, ..opts }, &invs).count(bug.target());
        let mut line = format!("| `{}` ({}) | {} |", bug.name(), bug.target(), none);
        for m in &mixes {
            let r = sweep(&cfg, &SweepOpts { mix: *m, ..opts }, &invs);
            write!(line, " {} |", r.count(bug.target())).unwrap();
        }
        writeln!(w, "{line}").unwrap();
    }

    writeln!(w, "\n## 4. Reproduce\n").unwrap();
    writeln!(w, "```sh").unwrap();
    writeln!(
        w,
        "scripts/report.sh --check     # fails if this file is stale"
    )
    .unwrap();
    writeln!(
        w,
        "cargo run --release -p shoke-cli -- sweep --profile kev-cold --require-floor"
    )
    .unwrap();
    writeln!(
        w,
        "cargo run --release -p shoke-cli -- sweep --bug retry-storm --mix http --shrink"
    )
    .unwrap();
    writeln!(w, "```").unwrap();
    out
}
